# Generated by Django 4.2.7 on 2025-11-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_pushtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
