# Generated by Django 4.2.7 on 2025-10-16 16:10

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactattachment',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='ua',
        ),
        migrations.AddField(
            model_name='contactattachment',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='client_request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='locale',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='contactattachment',
            name='file',
            field=models.FileField(upload_to=contact.models.contact_upload_path),
        ),
        migrations.AlterField(
            model_name='contactattachment',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactattachment',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
