# Generated by Django 4.1.7 on 2025-09-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bodyweight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso corporal (kg)'),
        ),
    ]
