# Generated by Django 4.1.7 on 2025-09-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo nombre'),
        ),
    ]
