# Generated by Django 4.1.7 on 2025-09-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_bodyweight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bench_1rm',
            field=models.FloatField(blank=True, null=True, verbose_name='1RM inicial Bench'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deadlift_1rm',
            field=models.FloatField(blank=True, null=True, verbose_name='1RM inicial Deadlift'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='squat_1rm',
            field=models.FloatField(blank=True, null=True, verbose_name='1RM inicial Squat'),
        ),
    ]
