# Generated by Django 4.2.7 on 2025-09-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_bench_1rm_customuser_deadlift_1rm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='1RM inicial Deadlift'),
        ),
    ]
