# Generated by Django 4.2.7 on 2025-09-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Codigo expirado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Codigo de recuperación'),
        ),
    ]
