# Generated by Django 4.2.7 on 2025-10-03 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_quality', models.IntegerField(help_text='Calidad del sueño 1-10')),
                ('fatigue', models.IntegerField(help_text='Fatiga 1-10')),
                ('stress', models.IntegerField(help_text='Estrés 1-10')),
                ('soreness', models.TextField(blank=True, help_text='Molestias o dolores', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='aisuggestion',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='aisuggestion',
            name='block',
        ),
        migrations.RemoveField(
            model_name='aisuggestion',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='aisuggestion',
            name='session',
        ),
        migrations.DeleteModel(
            name='AIAdjustmentLog',
        ),
        migrations.DeleteModel(
            name='AISuggestion',
        ),
    ]
