# Generated by Django 4.2.7 on 2025-10-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_coachathlete_end_date'),
        ('ai', '0003_athletefeedback_remove_aisuggestion_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletefeedback',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='training.trainingsession'),
        ),
    ]
