# Generated by Django 4.2.7 on 2025-10-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_coachathlete_end_date'),
        ('ai', '0004_athletefeedback_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='training.exercise')),
            ],
        ),
    ]
