# Generated by Django 4.2.7 on 2025-10-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_exerciseadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseadjustment',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
