# Generated by Django 4.2.7 on 2025-10-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_coachathlete_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingblock',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
