# Generated by Django 4.2.7 on 2025-10-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingblock_completed_trainingsession_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
