# Generated by Django 4.2.7 on 2025-10-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingsession_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='is_active',
            new_name='started',
        ),
    ]
