# Generated by Django 4.2.7 on 2025-10-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_rename_is_active_trainingsession_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='started',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Finalizada')], default='pending', max_length=20),
        ),
    ]
