# Generated by Django 4.2.7 on 2025-11-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_remove_trainingsession_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprogress',
            name='exercise',
            field=models.CharField(choices=[('Sentadilla', 'Sentadilla'), ('Press Banca', 'Press Banca'), ('Peso Muerto', 'Peso Muerto')], max_length=100),
        ),
    ]
