# Generated by Django 4.2.7 on 2025-11-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_trainingsession_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprogress',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.trainingblock'),
        ),
    ]
