# Generated by Django 4.2.7 on 2025-11-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_athleteprogress_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprogress',
            name='exercise',
            field=models.CharField(choices=[('Sentadilla', 'Sentadilla'), ('Bench Press', 'Bench Press'), ('Peso muerto', 'Peso muerto')], max_length=100),
        ),
    ]
